// F3 - Briefing
// Credits: Please see the F3 online manual (http://www.ferstaberinde.com/f3/en/)
//
//
// DO NOT EDIT THIS FILE. FIND BRIEFING EDITS IN F\BRIEFING.
//
//
// ====================================================================================

if (!isDedicated && (isNull player)) then
{
    waitUntil {sleep 0.1; !isNull player};
};


private ["_unitfaction"];

waitUntil {!isnil "f_var_debugMode"};

_unitfaction = toLower (faction player);

if (_unitfaction != toLower (faction (leader group player))) then {_unitfaction = toLower (faction (leader group player))};

// DEBUG

	if (f_var_debugMode == 1) then
	{
	player sideChat format ["DEBUG (briefing.sqf): Player faction: %1",_unitfaction];
	};


// BRIEFING: ADMIN

if (serverCommandAvailable "#kick") then {

#include "f\briefing\f_briefing_admin.sqf"

// DEBUG
	if (f_var_debugMode == 1) then
	{
		player sideChat format ["DEBUG (briefing.sqf): Briefing for host selected.",_unitfaction];
	};
};

// BRIEFING: BLUFOR > NATO

if (_unitfaction == "blu_f") exitwith {

#include "f\briefing\f_briefing_nato.sqf"

// DEBUG
	if (f_var_debugMode == 1) then
	{
	player sideChat format ["DEBUG (briefing.sqf): Briefing for %1 slot selected.",_unitfaction];
	};
};

// BRIEFING: OPFOR > CSAT

if (_unitfaction == "opf_f") exitwith {

#include "f\briefing\f_briefing_csat.sqf"

// DEBUG
	if (f_var_debugMode == 1) then
	{
	player sideChat format ["DEBUG (briefing.sqf): Briefing for %1 slot selected.",_unitfaction];
	};
};

// BRIEFING: INDEPENDENT > AAF

if (_unitfaction == "ind_f") exitwith {

#include "f\briefing\f_briefing_aaf.sqf"

// DEBUG
	if (f_var_debugMode == 1) then
	{
	player sideChat format ["DEBUG (briefing.sqf): Briefing for %1 slot selected.",_unitfaction];
	};
};

// BRIEFING: CIVILIAN

if (_unitfaction == "civ_f") exitwith {

#include "f\briefing\f_briefing_civ.sqf"

// DEBUG
	if (f_var_debugMode == 1) then
	{
	player sideChat format ["DEBUG (briefing.sqf): Briefing for %1 slot selected.",_unitfaction];
	};
};

// BRIEFING: ZEUS

if (_unitfaction == "") exitwith {

#include "f\briefing\f_briefing_zeus.sqf"

// DEBUG
	if (f_var_debugMode == 1) then
	{
	player sideChat format ["DEBUG (briefing.sqf): Briefing for %1 slot selected.",_unitfaction];
	};
};

// ERROR CHECKING

player globalchat format ["DEBUG (briefing.sqf): Faction %1 is not defined.",_unitfaction];